avitoCar_dbt:
  outputs:
    dev:
      dbname: avitocardatasetALL
      host: localhost      #host.docker.internal
      password: 2025@2025
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev